services:
  - type: web
    name: uniportal-backend
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: free
    healthCheckPath: /health
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: ConnectionStrings__DefaultConnection
        value: "Server=crossover.proxy.rlwy.net;Port=44070;Database=railway;Uid=root;Pwd=wtWYuztNPZkFwJXTayCFeYXiSgrBIbLg;"

  - type: web
    name: uniportal-frontend
    runtime: docker
    dockerfilePath: ./frontend/Dockerfile
    plan: free
    envVars:
      - key: DB_HOST
        value: crossover.proxy.rlwy.net
      - key: DB_PORT
        value: "44070"
      - key: DB_NAME
        value: railway
      - key: DB_USER
        value: root
      - key: DB_PASS
        value: wtWYuztNPZkFwJXTayCFeYXiSgrBIbLg
