[phases.setup]
nixPkgs = ["dotnet-sdk_9"]

[phases.install]
cmds = ["dotnet restore"]

[phases.build]
cmds = ["dotnet build --configuration Release --no-restore"]

[start]
cmd = "dotnet run --project UniPortalBackend.csproj --configuration Release"
